/* 
Name: types
Action: types of redux actions
*/

export const ADD_ORGANIZATION = 'ADD_ORGANIZATION';
export const REMOVE_ORGANIZATION = 'REMOVE_ORGANIZATION';

export const ADD_USERINFO = 'ADD_USERINFO';
export const REMOVE_USERINFO = 'REMOVE_USERINFO';

export const ADD_PERMISSIONS = 'ADD_PERMISSIONS';
export const REMOVE_PERMISSIONS = 'REMOVE_PERMISSIONS';

export const DO_NOTHING = 'DO_NOTHING';

export const PUSH_NOTIFICATION = 'PUSH_NOTIFICATION';
export const REMOVE_NOTIFICATION = 'REMOVE_NOTIFICATION';
export const CLEAR_NOTIFICATIONS = 'CLEAR_NOTIFICATIONS';

export const SET_ENABLE_ACTIONS = 'SET_ENABLE_ACTIONS';
export const CLEAR_ENABLE_ACTIONS = 'CLEAR_ENABLE_ACTIONS';

export const ADD_DIMENSION_OBJECT = 'ADD_DIMENSION_OBJECT';
export const REPLACE_DIMENSION_OBJECT = 'REPLACE_DIMENSION_OBJECT';
export const RESTAURE_DEFAULT_OBJECT = 'RESTAURE_DEFAULT_OBJECT';

export const STATE_MAIN_BAR = 'STATE_MAIN_BAR';
export const CLEAR_STATE_MAIN_BAR = 'CLEAR_STATE_MAIN_BAR';
export const SET_SELECTED_OPTION = 'SET_SELECTED_OPTION';
export const SET_DASHBOARD_LOADING = 'SET_DASHBOARD_LOADING';

export const SET_LANGUAGE = 'SET_LANGUAGE';

// Filter actions
export const ADD_GROUP = 'FILTERS/ADD_GROUP';
export const ADD_RULE = 'FILTERS/ADD_RULE';
export const UPDATE_RULE = 'FILTERS/UPDATE_RULE';
export const UPDATE_GROUP = 'FILTERS/UPDATE_GROUP';
export const DELETE_NODE = 'FILTERS/DELETE_NODE';
export const RESET_FILTERS = 'FILTERS/RESET_FILTERS';
export const CLEAN_BROKEN_REFERENCES = 'FILTERS/CLEAN_BROKEN_REFERENCES';
export const SET_SEARCH = 'FILTERS/SET_SEARCH';

export const SET_APP_ID = 'SET_APP_ID';
export const CLEAR_APP_ID = 'CLEAR_APP_ID';

// Application Services actions
export const SET_APPLICATION_SERVICES = 'SET_APPLICATION_SERVICES';
export const CLEAR_APPLICATION_SERVICES = 'CLEAR_APPLICATION_SERVICES';